/**
 * This tool is used to generate the client-side Graphql types and hooks.
 */
import { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: 'dist/apps/api/autogenerated-schema.gql',
  documents: ['apps/**/*gql.ts', 'libs/**/*gql.ts'],
  ignoreNoDocuments: true,
  generates: {
    // Client-side types
    './libs/web/data-access-graphql/src/lib/types.ts': {
      plugins: ['typescript'],
    },
    './libs/': {
      preset: 'near-operation-file',
      presetConfig: {
        extension: '.gen.ts',
        baseTypesPath: 'web/data-access-graphql/src/lib/types.ts',
      },
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-graphql-request',
      ],
      config: {
        withHooks: true,
        gqlImport: 'graphql-request#gql',
      },
    },
  },
};

export default config;
